name: Publish Nuget Package

on:
  push:
    branches:
      - dev
      - develop

env:
  SOLUTION_FOLDER: 'src/Schlechtums.FastDynamicAccess'
  DOTNET_VERSION: "3.1.301" # set this to the dotnet version to use

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish NuGet package
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/schlechtums/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}

      - name: Build Solution
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet build -nologo -c Release

      - name: Unit Test
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet test -nologo -c Release

      - name: Push generated package to GitHub registry
        run: find . -name '*.nupkg' -exec nuget push {} -SkipDuplicate -NoSymbols \;
