
# This is a basic workflow to help you get started with Actions

name: Publish Nuget Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev, develop ]

env:
  SOLUTION_FOLDER: 'src/Schlechtums.FastDynamicAccess'
  VERSION: '2.0.0'
  DOTNET_VERSION: "3.1.301" # set this to the dotnet version to use

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/schlechtums/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}        

      - name: Unit Test
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet test -nologo -c Release
        
      - name: Build Solution
        run: cd ${{ env.SOLUTION_FOLDER }}; dotnet build -nologo -c Release /property:Version=${{ env.VERSION }}.$GITHUB_RUN_NUMBER

      - name: Push generated package to GitHub registry
        run: find . -name '*.nupkg' -exec nuget push {} -SkipDuplicate -NoSymbols \;
